import Head from "next/head";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.css";
import {LinePlot} from "@/components/Plot";
import {useState} from "react";
import * as d3 from "d3";
import {Bar} from "@/components/Bar";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
  const [data, setData] = useState(() => d3.ticks(-2, 2, 200).map(Math.sin));

  const onMouseMove = (event: any) => {
    const [x, y] = d3.pointer(event);
    setData(data.slice(-200).concat(Math.atan2(x, y)));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div onMouseMove={onMouseMove}>{/* <LinePlot data={data} /> */}</div>
        <div onMouseMove={onMouseMove}>
          <Bar data={data} />
        </div>
      </main>
    </>
  );
}
